version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-replica
    ports:
      - 27017:27017
    volumes:
      - ./initialize.js:/docker-entrypoint-initdb.d/initialize.js:ro
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

volumes:
  mongo-data:
